#language: ruby
dist: xenial

branches:
  only:
  - master

jobs:
  include:
  - name: build site
    language: python
    python:
      - "3.5.2"
    env:
      global:
        - PATH=$HOME/.local/user/bin:$PATH
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
        - secure: "MF1jZfPfG1vCIiF6dxVDSEqVAk+S6GieoGkmQxGbYMLM7P43o4tffOHoEAXZ/B2qZoj9fp4SiGA1VymNZhoMuPN0fy/vOSPEFUvT0QmVuz3EutXFJernSVYxkIjuVno4BJ4FtB/DCQEXlxoJiKR9blAo1EGvDjVelNbkgwlLl/0="
        - secure: "YNK2OSRdbQ8WeXQvkH6tR/WaB+07uU4+Lz1wdDXZ3+xRrwenobKfaGYj7CAXVIXbYOEcDUushgRlnYHhjy7lwxOIkyZ2aS7iSifcBd4IgRu7LveMDFMcLgR+z5ipC9ml+QIjeIKf577Qfl+Ojc/2uka9CDtSD+loNccpNnOwa2M="
        - secure: "kN2QQur7joKgs4DRxV0Wq18pYWSiNKr75ZndxYP9d7L6/FtuYqHeA41pY9OLSrY+Vxl+kxHhYxOF6UpG53oGwF4dvkHMLiJ7uGF/skvhvCp+keFryEAy6hA/VO0Z+EzCe1KvfDlMN8thBPpzH94ukwM/BuBshbY6O+oLouOpaaw="
        - secure: "R31quoen3lDAJWyuJ/E41dT3bOaGek+nCQ2lzOMnwiTEKjTCumuh99H/bymJLZLcfHj0k0q+bE9cgdQ5JrAvx5c1/0j5jIz15kCHDWy8P6UHFXAopPuYP+q48NnW/9gPj/bVaq6P+eNpjK8Phga8HBGtuxRQHEgFeRpj3vNAqhM="
    cache:
      pip: true
      directories:
        - vendor/bundle
        - node_modules
        - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
    addons:
      apt:
        packages:
          - libxml2-utils
    install:
      - rvm use 2.6.3 --install
      - bundle install --deployment
      - sudo apt-get install libcurl4-openssl-dev # required to avoid SSL errors
    script:
      - bundle exec rake test
      - xmllint --noout _site/feed.build-env-updates.xml
    deploy:
      provider: heroku
      api_key:
        secure: "hylw2GIHMvZKOKX3uPSaLEzVrUGEA9mzGEA0s4zK37W9HJCTnvAcmgRCwOkRuC4L7R4Zshdh/CGORNnBBgh1xx5JGYwkdnqtjHuUQmWEXCusrIURu/iEBNSsZZEPK7zBuwqMHj2yRm64JfbTDJsku3xdoA5Z8XJG5AMJGKLFgUQ="
      app: docs-travis-ci-com
      on:
        branch:
        - master
      edge: true

  - name: update dpl v2 docs
    if: type = cron || commit_message =~ /ci:dpl/
    language: shell
    cache: false
    install:
    - rvm use 2.5.3
    script:
    - git clone https://github.com/travis-ci/dpl.git
    - cd dpl
    - gem build dpl.gemspec
    - gem install dpl-*.gem
    - cd ..
    - rm -rf dpl
    - bin/dpl
    deploy:
    - provider: git_push
      token:
        secure: "YHuTjIGKpG0A8QJ4kmdLfOW1n+62uLakXv0KjCzWExl22qLSn2frip3j8JsaeMfndsmNZBUfGoONVHvDS+PHnkbRMYf21SjgctpVfHRYZQ3pulexOViEQ6azRgCBWuPO8A+vAyxvjlV4e3UDGnt2x/0X/Tdg9iVf/zzBGjM0YX0="
      branch: auto-dpl-v2-update-docs
      pull_request: true
      edge:
        branch: master

notifications:
  slack:
    rooms:
      secure: LPNgf0Ra6Vu6I7XuK7tcnyFWJg+becx1RfAR35feWK81sru8TyuldQIt7uAKMA8tqFTP8j1Af7iz7UDokbCCfDNCX1GxdAWgXs+UKpwhO89nsidHAsCkW2lWSEM0E3xtOJDyNFoauiHxBKGKUsApJTnf39H+EW9tWrqN5W2sZg8=
    on_success: never
  webhooks:
    https://docs.travis-ci.com/update_webhook_payload_doc
